name: Trigger auto deployment for todoappspacesdeploymentb5f08a5a

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/todoappspacesdeploymentb5f08a5a-AutoDeployTrigger-9e635237-c0f0-4672-bead-420b338cae34.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TODOAPPSPACESDEPLOYMENTB5F08A5A_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TODOAPPSPACESDEPLOYMENTB5F08A5A_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TODOAPPSPACESDEPLOYMENTB5F08A5A_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.TODOAPPSPACESDEPLOYMENTB5F08A5A_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TODOAPPSPACESDEPLOYMENTB5F08A5A_REGISTRY_PASSWORD }}
          containerAppName: todoappspacesdeploymentb5f08a5a
          resourceGroup: todoappspacesdeploymentb5f0
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


